# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\VC_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 720))
        MainWindow.setBaseSize(QtCore.QSize(1280, 720))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.log_window = QtWidgets.QTextBrowser(self.centralwidget)
        self.log_window.setGeometry(QtCore.QRect(1010, 10, 261, 661))
        self.log_window.setObjectName("log_window")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(7, 520, 991, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(990, 0, 20, 681))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 954, 513))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.LightController = QtWidgets.QWidget(self.widget)
        self.LightController.setMinimumSize(QtCore.QSize(150, 510))
        self.LightController.setMaximumSize(QtCore.QSize(150, 510))
        self.LightController.setStyleSheet("color: rgb(0, 195, 227)")
        self.LightController.setObjectName("LightController")
        self.gridLayout.addWidget(self.LightController, 0, 0, 2, 1)
        self.CameraCommandLayout = QtWidgets.QHBoxLayout()
        self.CameraCommandLayout.setObjectName("CameraCommandLayout")
        self.CameraList = QtWidgets.QComboBox(self.widget)
        self.CameraList.setMinimumSize(QtCore.QSize(300, 0))
        self.CameraList.setMaximumSize(QtCore.QSize(16777215, 25))
        self.CameraList.setObjectName("CameraList")
        self.CameraCommandLayout.addWidget(self.CameraList)
        self.ReadCamera = QtWidgets.QPushButton(self.widget)
        self.ReadCamera.setMaximumSize(QtCore.QSize(75, 25))
        self.ReadCamera.setObjectName("ReadCamera")
        self.CameraCommandLayout.addWidget(self.ReadCamera)
        self.CameraCapture_2 = QtWidgets.QPushButton(self.widget)
        self.CameraCapture_2.setMaximumSize(QtCore.QSize(75, 25))
        self.CameraCapture_2.setObjectName("CameraCapture_2")
        self.CameraCommandLayout.addWidget(self.CameraCapture_2)
        self.CameraRecord = QtWidgets.QPushButton(self.widget)
        self.CameraRecord.setMaximumSize(QtCore.QSize(75, 25))
        self.CameraRecord.setObjectName("CameraRecord")
        self.CameraCommandLayout.addWidget(self.CameraRecord)
        self.OpenCaptureFolder = QtWidgets.QToolButton(self.widget)
        self.OpenCaptureFolder.setMaximumSize(QtCore.QSize(25, 25))
        self.OpenCaptureFolder.setObjectName("OpenCaptureFolder")
        self.CameraCommandLayout.addWidget(self.OpenCaptureFolder)
        self.gridLayout.addLayout(self.CameraCommandLayout, 0, 1, 1, 1)
        self.RightController = QtWidgets.QWidget(self.widget)
        self.RightController.setMinimumSize(QtCore.QSize(150, 510))
        self.RightController.setMaximumSize(QtCore.QSize(150, 510))
        self.RightController.setStyleSheet("color: rgb(255, 69, 84)")
        self.RightController.setObjectName("RightController")
        self.gridLayout.addWidget(self.RightController, 0, 2, 2, 1)
        self.CameraCapture = QtWidgets.QOpenGLWidget(self.widget)
        self.CameraCapture.setMinimumSize(QtCore.QSize(640, 480))
        self.CameraCapture.setMaximumSize(QtCore.QSize(1280, 720))
        self.CameraCapture.setObjectName("CameraCapture")
        self.gridLayout.addWidget(self.CameraCapture, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "VController"))
        self.ReadCamera.setText(_translate("MainWindow", "Connect"))
        self.CameraCapture_2.setText(_translate("MainWindow", "Capture"))
        self.CameraRecord.setText(_translate("MainWindow", "Rec"))
        self.OpenCaptureFolder.setText(_translate("MainWindow", "..."))

